server:
  port: 5052

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieapp?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userdetails